create table public.users (
  id uuid not null default gen_random_uuid (),
  name text null,
  email text null,
  created_at timestamp with time zone not null default now(),
  constraint user_pkey primary key (id)
) TABLESPACE pg_default;

create table public.contact_messages (
  id bigint generated by default as identity not null,
  message text not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid null default gen_random_uuid (),
  constraint contact_pkey primary key (id),
  constraint contact_messages_user_id_fkey foreign KEY (user_id) references users (id)
) TABLESPACE pg_default;

create table public.chat_messages (
  id bigint generated by default as identity not null,
  role text not null,
  content text not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null default gen_random_uuid (),
  constraint message_pkey primary key (id)
) TABLESPACE pg_default;